#!/bin/sh; C:/Program\ Files/Git/usr/bin/sh.exe
echo "Running precommit hook..."
LC_ALL=C

# Select files to format from staged area
GITFILES=$(git diff --name-only --staged --diff-filter=ACM "*.cs" | sed 's| |\\ |g') 
# remove root src dir from git file path when passing to dotnet format
[ -z "$GITFILES" ] && exit 0

dotnet-format -v diag -f ./Ajax-TheGame/Assets/Scripts

# Add back the modified files to staging
echo "$GITFILES" | xargs git add
exit 0